services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_TRIP_URL: "https://<TRIP_API_DOMAIN>"
        VITE_DRIVER_URL: "https://<DRIVER_API_DOMAIN>"
        VITE_RIDER_URL: "https://<RIDER_API_DOMAIN>"
    ports:
      - "8080:80"
    restart: unless-stopped